// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgnbGmpNMOtSBhdOhz_5rT1U0hsh-wdac',
    appId: '1:729301452834:web:643bbf5497431fd305627b',
    messagingSenderId: '729301452834',
    projectId: 'shopgo-369',
    authDomain: 'shopgo-369.firebaseapp.com',
    storageBucket: 'shopgo-369.firebasestorage.app',
    measurementId: 'G-MTQ4N0S3P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD0Ils6JPKYm09BggTHCFX4dL5-lKkn6Q',
    appId: '1:729301452834:android:58ac603add2f581105627b',
    messagingSenderId: '729301452834',
    projectId: 'shopgo-369',
    storageBucket: 'shopgo-369.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOl8whBICI5zsxGWJ17KWWSTg4jI56uuM',
    appId: '1:729301452834:ios:87ea0a01acc8288805627b',
    messagingSenderId: '729301452834',
    projectId: 'shopgo-369',
    storageBucket: 'shopgo-369.firebasestorage.app',
    iosBundleId: 'com.shopgo369.platform369Mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgnbGmpNMOtSBhdOhz_5rT1U0hsh-wdac',
    appId: '1:729301452834:web:8ec9fbde8fa9336b05627b',
    messagingSenderId: '729301452834',
    projectId: 'shopgo-369',
    authDomain: 'shopgo-369.firebaseapp.com',
    storageBucket: 'shopgo-369.firebasestorage.app',
    measurementId: 'G-LL9K4CM86R',
  );
}
